/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#171C3F',
        'primary-container': '#EEEEF6',
        'on-primary': '#ffffff',
        'on-primary-container': '#171C3F',
        'on-primary-fixed': '#0D1026',
        'on-primary-fixed-variant': '#2A3060',
        'primary-fixed': '#DDDEED',
        'primary-fixed-dim': '#9698C3',
        'inverse-primary': '#9698C3',
        'secondary': '#4a607a',
        'secondary-container': '#c7dffd',
        'secondary-fixed': '#d0e4ff',
        'secondary-fixed-dim': '#b1c9e6',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#4c637d',
        'on-secondary-fixed': '#021d33',
        'on-secondary-fixed-variant': '#324861',
        'tertiary': '#0F172A',
        'tertiary-container': '#1E293B',
        'tertiary-fixed': '#CBD5E1',
        'tertiary-fixed-dim': '#94A3B8',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#94A3B8',
        'on-tertiary-fixed': '#0F172A',
        'on-tertiary-fixed-variant': '#334155',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface': '#f9faf7',
        'surface-dim': '#d9dad8',
        'surface-bright': '#f9faf7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f2',
        'surface-container': '#edeeec',
        'surface-container-high': '#e7e8e6',
        'surface-container-highest': '#e1e3e1',
        'surface-variant': '#e1e3e1',
        'surface-tint': '#171C3F',
        'on-surface': '#191c1b',
        'on-surface-variant': '#404946',
        'inverse-surface': '#2e3130',
        'inverse-on-surface': '#f0f1ef',
        'background': '#f9faf7',
        'on-background': '#191c1b',
        'outline': '#707976',
        'outline-variant': '#c0c8c4',
        'warning': '#956B1D',
        'warning-container': '#FFDEA6',
        'on-warning-container': '#4E3900',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
