/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': 'rgb(var(--primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--primary-container) / <alpha-value>)',
        'on-primary': '#ffffff',
        'on-primary-container': 'rgb(var(--on-primary-container) / <alpha-value>)',
        'on-primary-fixed': 'rgb(var(--on-primary-fixed) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--on-primary-fixed-variant) / <alpha-value>)',
        'primary-fixed': 'rgb(var(--primary-fixed) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--primary-fixed-dim) / <alpha-value>)',
        'inverse-primary': 'rgb(var(--inverse-primary) / <alpha-value>)',
        'secondary': 'rgb(var(--secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--secondary-container) / <alpha-value>)',
        'secondary-fixed': '#E0E7FF',
        'secondary-fixed-dim': '#A5B4FC',
        'on-secondary': '#ffffff',
        'on-secondary-container': 'rgb(var(--on-secondary-container) / <alpha-value>)',
        'on-secondary-fixed': '#312E81',
        'on-secondary-fixed-variant': '#4338CA',
        'tertiary': '#0EA5E9',
        'tertiary-container': '#F0F9FF',
        'tertiary-fixed': '#E0F2FE',
        'tertiary-fixed-dim': '#7DD3FC',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#0284C7',
        'on-tertiary-fixed': '#0C4A6E',
        'on-tertiary-fixed-variant': '#0369A1',
        'error': '#EF4444',
        'error-container': '#FEF2F2',
        'on-error': '#ffffff',
        'on-error-container': '#DC2626',
        'surface': '#F8FAFC',
        'surface-dim': '#E2E8F0',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F8FAFC',
        'surface-container': '#F1F5F9',
        'surface-container-high': '#E2E8F0',
        'surface-container-highest': '#CBD5E1',
        'surface-variant': '#F1F5F9',
        'surface-tint': 'rgb(var(--primary) / <alpha-value>)',
        'on-surface': '#0F172A',
        'on-surface-variant': '#64748B',
        'inverse-surface': '#1E293B',
        'inverse-on-surface': '#F8FAFC',
        'background': '#F8FAFC',
        'on-background': '#0F172A',
        'outline': '#94A3B8',
        'outline-variant': '#E2E8F0',
        'warning': '#F59E0B',
        'warning-container': '#FFFBEB',
        'on-warning-container': '#D97706',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        '4xl': '2rem',
      },
      boxShadow: {
        'card': '0 1px 3px 0 rgba(0, 0, 0, 0.04), 0 1px 2px -1px rgba(0, 0, 0, 0.03)',
        'card-hover': '0 4px 12px -2px rgba(0, 0, 0, 0.08), 0 2px 4px -2px rgba(0, 0, 0, 0.04)',
        'elevated': '0 4px 16px -4px rgba(0, 0, 0, 0.08), 0 2px 6px -2px rgba(0, 0, 0, 0.04)',
        'modal': '0 20px 60px -12px rgba(0, 0, 0, 0.15), 0 8px 20px -8px rgba(0, 0, 0, 0.08)',
        'soft': '0 0 0 1px rgba(0, 0, 0, 0.03), 0 1px 2px rgba(0, 0, 0, 0.04)',
      },
    },
  },
  plugins: [],
};
