import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** @type {import('tailwindcss').Config} */
export default {
  content: [path.join(__dirname, 'src/**/*.{astro,html,js,ts}')],
  theme: {
    extend: {
      colors: {
        'primary': '#05213a',
        'primary-container': '#1e3750',
        'on-primary': '#ffffff',
        'on-primary-container': '#88a0be',
        'on-primary-fixed': '#011d35',
        'on-primary-fixed-variant': '#314863',
        'primary-fixed': '#d1e4ff',
        'primary-fixed-dim': '#b0c9e8',
        'inverse-primary': '#b0c9e8',
        'secondary': '#4a607a',
        'secondary-container': '#c7dffd',
        'secondary-fixed': '#d0e4ff',
        'secondary-fixed-dim': '#b1c9e6',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#4c637d',
        'on-secondary-fixed': '#021d33',
        'on-secondary-fixed-variant': '#324861',
        'tertiary': '#002520',
        'tertiary-container': '#003d35',
        'tertiary-fixed': '#a0f2e1',
        'tertiary-fixed-dim': '#84d5c5',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#5bac9d',
        'on-tertiary-fixed': '#00201b',
        'on-tertiary-fixed-variant': '#005046',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface': '#f9faf7',
        'surface-dim': '#d9dad8',
        'surface-bright': '#f9faf7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f2',
        'surface-container': '#edeeec',
        'surface-container-high': '#e7e8e6',
        'surface-container-highest': '#e1e3e1',
        'surface-variant': '#e1e3e1',
        'surface-tint': '#49607c',
        'on-surface': '#191c1b',
        'on-surface-variant': '#404946',
        'inverse-surface': '#2e3130',
        'inverse-on-surface': '#f0f1ef',
        'background': '#f9faf7',
        'on-background': '#191c1b',
        'outline': '#707976',
        'outline-variant': '#c0c8c4',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
