import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** @type {import('tailwindcss').Config} */
export default {
  content: [path.join(__dirname, 'src/**/*.{astro,html,js,ts}')],
  theme: {
    extend: {
      colors: {
        'primary': '#006948',
        'primary-container': '#00855d',
        'on-primary': '#ffffff',
        'on-primary-container': '#f5fff7',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#005137',
        'primary-fixed': '#85f8c4',
        'primary-fixed-dim': '#68dba9',
        'inverse-primary': '#68dba9',
        'secondary': '#3e5f56',
        'secondary-container': '#d9ebe4',
        'secondary-fixed': '#d9ebe4',
        'secondary-fixed-dim': '#bdd3ca',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#2f4a43',
        'on-secondary-fixed': '#13231e',
        'on-secondary-fixed-variant': '#355047',
        'tertiary': '#0d766e',
        'tertiary-container': '#c7efe9',
        'tertiary-fixed': '#daf8f3',
        'tertiary-fixed-dim': '#8dded2',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#0a4f49',
        'on-tertiary-fixed': '#042b27',
        'on-tertiary-fixed-variant': '#0b5e57',
        'error': '#dc2626',
        'error-container': '#fef2f2',
        'on-error': '#ffffff',
        'on-error-container': '#991b1b',
        'surface': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#006c4a',
        'on-surface': '#191c1e',
        'on-surface-variant': '#3d4a42',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'background': '#f7f9fb',
        'on-background': '#191c1e',
        'outline': '#6d7a72',
        'outline-variant': '#bccac0',
        'accent': '#006948',
        'accent-light': '#00855d',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
