import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** @type {import('tailwindcss').Config} */
export default {
  content: [path.join(__dirname, 'src/**/*.{astro,html,js,ts}')],
  theme: {
    extend: {
      colors: {
        'primary': '#1e293b',
        'primary-container': '#334155',
        'on-primary': '#ffffff',
        'on-primary-container': '#94a3b8',
        'on-primary-fixed': '#0f172a',
        'on-primary-fixed-variant': '#475569',
        'primary-fixed': '#e2e8f0',
        'primary-fixed-dim': '#cbd5e1',
        'inverse-primary': '#cbd5e1',
        'secondary': '#475569',
        'secondary-container': '#e0e7ff',
        'secondary-fixed': '#e0e7ff',
        'secondary-fixed-dim': '#c7d2fe',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#4338ca',
        'on-secondary-fixed': '#1e1b4b',
        'on-secondary-fixed-variant': '#3730a3',
        'tertiary': '#4f46e5',
        'tertiary-container': '#4338ca',
        'tertiary-fixed': '#c7d2fe',
        'tertiary-fixed-dim': '#a5b4fc',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#c7d2fe',
        'on-tertiary-fixed': '#1e1b4b',
        'on-tertiary-fixed-variant': '#3730a3',
        'error': '#dc2626',
        'error-container': '#fef2f2',
        'on-error': '#ffffff',
        'on-error-container': '#991b1b',
        'surface': '#fafbfc',
        'surface-dim': '#e2e8f0',
        'surface-bright': '#fafbfc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f1f5f9',
        'surface-container': '#e2e8f0',
        'surface-container-high': '#cbd5e1',
        'surface-container-highest': '#94a3b8',
        'surface-variant': '#f1f5f9',
        'surface-tint': '#4f46e5',
        'on-surface': '#0f172a',
        'on-surface-variant': '#475569',
        'inverse-surface': '#1e293b',
        'inverse-on-surface': '#f8fafc',
        'background': '#fafbfc',
        'on-background': '#0f172a',
        'outline': '#64748b',
        'outline-variant': '#e2e8f0',
        'accent': '#4f46e5',
        'accent-light': '#6366f1',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
