-- Add new society roles to the Role enum
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SECRETARY';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'JOINT_SECRETARY';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'TREASURER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SERVICE_STAFF';

-- Add specialization column for SERVICE_STAFF trade/skill
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "specialization" TEXT;
